### ISSUE TITLE
OS X not compiling 

### ISSUE THREAD

**Issue by ajbraus** [cryptonotefoundation/cryptonotewallet#1]
Hi there, I'm having fun following your tutorials.

In the [cryptonotewallet tutorial](https://cryptonotestarter.org/create-wallet.html) I am totally stuck at the last step. When I run `mkdir build && cd build && cmake .. && make` it errors out saying:

```
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindQt5Gui.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Gui", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Gui" with any
  of the following names:

    Qt5GuiConfig.cmake
    qt5gui-config.cmake

  Add the installation prefix of "Qt5Gui" to CMAKE_PREFIX_PATH or set
  "Qt5Gui_DIR" to a directory containing one of the above files.  If "Qt5Gui"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Users/Penelope/coins/mcoin-wallet/build/CMakeFiles/CMakeOutput.log".
```

For the life of me I could not find a solution to this problem. I am on OSx El Capitan and I have Qt Creator and Qt (command line) installed. I tried adding Qt to my PATH but to no avail. 

Any help you can give is much appreciated Thx!

**Comment by ajbraus** [comment]
I figured this issue out! I just had to do:

`cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.6.0/` 

that told cmake where my qt5 was.

**Comment by zhmrab** [comment]
hey @ajbraus can you please give me a little more detail on telling cmake where qt5 is on Mac?

I am stuck at the same errors ...
Thanks!!

**Comment by yx79** [comment]
brew install qt 
you can locate qt5 at /usr/local/Cellar/qt/5.10.0_1
but i am stucking after this. anyone have progress?

**Comment by murilob** [comment]
Same error here

**Comment by murilob** [comment]
ok. the command cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.6.0/
did not work for me. I had to open the CMakeList.txt and set it with:
set (CMAKE_PREFIX_PATH "/usr/local/Cellar/qt/5.9.2/")
