### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonotewallet#17]
I'm getting this error running this command

mkdir build && cd build && cmake .. && make
======
here's the error log

cryptonote/src/crypto/crypto.cpp:326:58: error: value-initialization of incomplete type 'Crypto::rs_comm::<anonymous struct> []'
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);

src/CMakeFiles/Crypto.dir/build.make:158: recipe for target 'src/CMakeFiles/Crypto.dir/crypto/crypto.cpp.o' failed
make[2]: *** [src/CMakeFiles/Crypto.dir/crypto/crypto.cpp.o] Error 1
CMakeFiles/Makefile2:528: recipe for target 'src/CMakeFiles/Crypto.dir/all' failed
make[1]: *** [src/CMakeFiles/Crypto.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jared201** [comment]
never mind...fixed.

**Comment by ghost** [comment]
how did you fix it?

**Comment by BenJackGill** [comment]
Same problem here, how did you fix it?
